# Generated by Django 3.1.1 on 2020-09-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='application',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='latin_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
