# Generated by Django 3.1.1 on 2020-09-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0002_auto_20200903_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='application',
            field=models.CharField(default='brak danych', max_length=128),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
