# Generated by Django 3.1.1 on 2020-09-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0004_auto_20200905_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroom',
            name='type',
        ),
    ]
