# Generated by Django 3.1.1 on 2020-09-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0006_mushroom_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroom',
            name='type',
        ),
    ]
