# Generated by Django 3.1.1 on 2020-09-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0008_borowik_maslak_mleczaj_muchomor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podgrzybek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('latin_name', models.CharField(blank=True, max_length=256)),
                ('application', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
    ]
