# Generated by Django 3.1.1 on 2020-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0009_podgrzybek'),
    ]

    operations = [
        migrations.AddField(
            model_name='borowik',
            name='description_fruitcake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='details_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='existence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='hat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='pulp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='season',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='shaft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borowik',
            name='smell',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='borowik',
            name='taste',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='borowik',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='description_fruitcake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='details_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='existence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='hat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='pulp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='season',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='shaft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='smell',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='taste',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
