# Generated by Django 3.1.1 on 2020-10-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0011_auto_20201024_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroom',
            name='fruitcake',
        ),
    ]
