# Generated by Django 3.1.1 on 2020-10-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0012_remove_mushroom_fruitcake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borowik',
            name='fruitcake',
        ),
    ]
