# Generated by Django 3.1.1 on 2020-10-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0013_remove_borowik_fruitcake'),
    ]

    operations = [
        migrations.AddField(
            model_name='maslak',
            name='area_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='area_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='base_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='color_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='color_pulp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='color_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='description_fruitcake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='description_hat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='description_pulp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='description_shaft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='details_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='existence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='habitat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='incidence_time',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='milk',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='rim_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='season',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maslak',
            name='section_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='shape_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='shape_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='smell',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='taste',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='type_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='area_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='area_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='base_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='color_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='color_pulp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='color_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='description_fruitcake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='description_hat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='description_pulp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='description_shaft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='details_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='existence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='habitat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='incidence_time',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='milk',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='rim_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='season',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='section_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='shape_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='shape_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='smell',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='taste',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='type_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='area_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='area_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='base_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='color_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='color_pulp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='color_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='description_fruitcake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='description_hat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='description_pulp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='description_shaft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='details_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='existence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='habitat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='incidence_time',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='milk',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='rim_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='season',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='section_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='shape_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='shape_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='smell',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='taste',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='type_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='area_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='area_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='base_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='color_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='color_pulp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='color_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='description_fruitcake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='description_hat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='description_pulp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='description_shaft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='details_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='existence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='habitat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='incidence_time',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='milk',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='rim_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='season',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='section_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='shape_hat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='shape_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='smell',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='taste',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='type_shaft',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
