# Generated by Django 3.1.1 on 2020-10-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0014_auto_20201024_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borowik',
            name='description_hat',
        ),
        migrations.RemoveField(
            model_name='maslak',
            name='description_hat',
        ),
        migrations.RemoveField(
            model_name='mleczaj',
            name='description_hat',
        ),
        migrations.RemoveField(
            model_name='muchomor',
            name='description_hat',
        ),
        migrations.RemoveField(
            model_name='mushroom',
            name='description_hat',
        ),
        migrations.RemoveField(
            model_name='podgrzybek',
            name='description_hat',
        ),
    ]
