# Generated by Django 3.1.1 on 2020-10-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0016_mushroom_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('BOROWIK', 'borowik'), ('MASLAK', 'maślak'), ('MLECZAJ', 'mleczaj'), ('MUCHOMOR', 'muchomor'), ('PODGRZYBEK', 'podgrzybek')], max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='mushroom',
            name='category',
        ),
    ]
