# Generated by Django 3.1.1 on 2020-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0018_auto_20201029_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='borowik',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maslak',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mleczaj',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='muchomor',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='podgrzybek',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
