# Generated by Django 3.1.1 on 2020-10-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0020_auto_20201030_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borowik',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Maslak',
        ),
        migrations.DeleteModel(
            name='Mleczaj',
        ),
        migrations.DeleteModel(
            name='Muchomor',
        ),
        migrations.DeleteModel(
            name='MushroomTest',
        ),
        migrations.DeleteModel(
            name='Podgrzybek',
        ),
    ]
